name: n8n
version: 2025.5.1
slug: hass-addons-n8n
description: Self host your n8n instance
url: https://github.com/racksync/hass-addons-n8n
hassio_api: true
hassio_role: default
homeassistant: 2025.4.4
panel_icon: mdi:transit-connection-variant
advanced: true
homeassistant_api: true
apparmor: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
icon: icon.png
logo: icon.png
webui: "http://[HOST]:[PORT:5690]"
map:
  - ssl:ro
  - backup:rw
  - share:rw
  - media:rw
  - config:ro
watchdog: "http://[HOST]:[PORT:5690]"
ingress: true
ingress_port: 5690
ports:
  "5678/tcp": null
  "8081/tcp": 8081
ports_description:
  "5678/tcp": The port for all n8n traffic. Normally not exposed, as Home Assistant Ingress is more secure and is recommended. You may expose this port if you want to bypass the Ingress (not recommended for security reasons). See the documentation for more information.
  "8081/tcp": The port for n8n webhook and API-related traffic. Use this to allow running under Home Assistant Ingress while still allowing certain public communication channels to go through and function. See the documentation for more information.
options:
  timezone: Asia/Bangkok
  env_vars_list: []
  cmd_line_args: ""
schema:
  timezone: str
  env_vars_list:
    - "match(^[A-Z_0-9]+: .*$)"
  cmd_line_args: "str?" 